### ISSUE TITLE
<!-- /TOC → appears on GitHub

### ISSUE THREAD

**Issue by lanceplaine** [nok/markdown-toc#32]
Hello,

Is it a bug?

Thanks

![screen shot 2015-06-25 at 8 49 05 pm](https://cloud.githubusercontent.com/assets/5476205/8370366/aeec3c96-1b7b-11e5-90d2-2f212cd86f9e.png)

**Comment by nok** [comment]
Hello @lanceplaine ,

I [tested](https://gist.github.com/nok/db0ae2983eb7cae74275) it. If you add the comment at the end of a line, it will be visible. Did you change the position of it or did it the package automatically?

Happy coding,
Darius

**Comment by lanceplaine** [comment]
Hi @nok,

It was automatically generated by the package

**Comment by lanceplaine** [comment]
https://gist.github.com/lanceplaine/60dbe448cdc405b57dfa

**Comment by nok** [comment]
Thank you, that is curious ...

**Comment by acanimal** [comment]
+1 to solve this. It is solved if you add a blank line between the last TOC item and the `<!-- TOC -->` string.

PS: This is a nice package that are helping me to move from ST to Atom :)

**Comment by joshbader** [comment]
+1
