### ISSUE TITLE
Code block comments treated as headings

### ISSUE THREAD

**Issue by eliotsykes** [nok/markdown-toc#45]
Treats code block comments beginning with `#` as headings. 

In the example below `# this is a code comment not a heading` is treated as a heading although it is inside a code block.

<pre>
# App Development Guide

## Another Heading

Hello World

```bash
# this is a code comment not a heading
ls -al
```

## And one more heading

Goodbye
</pre>

**Comment by ymattw** [comment]
+1

**Comment by slawo-ch** [comment]
+1

**Comment by torsday** [comment]
+1
