### ISSUE TITLE
Integrate jonschlinkert/markdown-toc

### ISSUE THREAD

**Issue by AppShipIt** [nok/markdown-toc#46]
Have you considered integrating the [TOC generator](https://github.com/jonschlinkert/markdown-toc) used by Assemble? It should reduce support and give a strong nudge beyond the [Sublime equivalent](https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py).

**Comment by Zettt** [comment]
@dnalot You can always fork the repo, make the edits necessary, and submit a pull request. That would be the easiest for all of us.
