### ISSUE TITLE
Only work with one file at a time

### ISSUE THREAD

**Issue by lanceplaine** [nok/markdown-toc#54]
For a unknown reason I can't use the `markdown-toc` plugin with multiples files at once.

The plugin works if I proceed the following way:
  - Open file 1
  - :white_check_mark: Use `markdown-toc` on file 1
  - Close file 1
  - Open file 2
  - :white_check_mark: Use `markdown-toc` on file 2
  - Close file 2
  - ...

The plugin doesn't work if I proceed the following way:
  - Open a folder with Atom
  - :white_check_mark: Use `markdown-toc` on file 1 (it's working)
  - :bug: Use `markdown-toc` on file 2 (it doesn't work)

---
_I use Atom 1.3.1 and Markdown TOC 0.4_

**Comment by lukehsiao** [comment]
I also have seen this issue. In addition, if I...
1. Open file 1
2. Use markdown-toc on file 1
3. Open file 2
4. attempt to use markdown-toc on file 2 (doesn't work, usually updates file 1 with the contents of file 2)
5. undo changes and close file 1
6. use markdown-toc on file 2

I get the error shown in #49, so they migth be related.

**Comment by pdelre** [comment]
+1

**Comment by getaaron** [comment]
+1 — I can reproduce this, and I get the error in #49, just like @lukehsiao

**Comment by getaaron** [comment]
Another thing I notice — if I press <kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>P</kbd>, when this will work I only see "Markdown TOC: Toggle". If it won't work, I see Create, Update, etc.

**Comment by timlyo** [comment]
I'd imagine that the issue is that the create function [here](https://github.com/nok/markdown-toc/blob/master/lib%2FToc.coffee#L28) isn't referencing the correct editor panel. Although I don't know enough about coffee script to fix it.

**Comment by bagong** [comment]
+1

**Comment by hkongm** [comment]
+1

**Comment by nkcoder** [comment]
+1

**Comment by xiaoyuzhzh** [comment]
+1

**Comment by dogoepp** [comment]
+1

**Comment by liuwenru** [comment]
+1

**Comment by shivabhusal** [comment]
In my case, I created TOC for a `something.md` file; I modified the headings and then I again try to generate TOC removing older one, I does not work.

If atom is once closed then it works fine for first time.

```
atom: 1.7.3
markdown-toc@0.4.1
```

**Comment by lanceplaine** [comment]
I submitted a [codemill](http://codemill.io) for $30. Hopefully it will motivate people to fix this little issue :)
https://github.com/lanceplaine/markdown-toc/issues/1
