### ISSUE TITLE
Use another delimiter

### ISSUE THREAD

**Issue by nicofrand** [nok/markdown-toc#59]
I am using this plugin and [https://github.com/travs/markdown-pdf/](markdown-pdf) to output some nice documents. However, markdown-pdf produces HTML and then convert the HTML to a PDF.

Since markdown-toc uses HTML comments (`<!--` and `-->`) as delimiters, the Table of contents never appears in the PDF :(.

Would that be possible to use another delimiter (maybe let the user define it in the settings) ?

**Comment by lanceplaine** [comment]
For my point of view the issue is on the other side (markdown-pdf) as it should not ignore the TOC content, only the TOC settings.

**Comment by nicofrand** [comment]
Oops my bad, I misread, I thought the content was actually inside the comments !
Sorry !
