### ISSUE TITLE
markdown-toc create doesn't working when atom open multi markdown files.

### ISSUE THREAD

**Issue by wlyan** [nok/markdown-toc#79]
markdown-toc create doesn't working when atom open multi markdown files.

+ 1. Open 2 markdown files `aa.md` and `bb.md` in atom tab.
+ 2. Create toc in `aa.md` success.
+ 3. Create toc in `bb.md` does not working.

**Comment by lanceplaine** [comment]
Seems like a duplicate of #54

**Comment by wlyan** [comment]
Yes, It's same as #54 , I will close this one.
